CREATE TABLE PROGRESS
    (
    	roll_no varchar(10) PRIMARY KEY,
    	name varchar(20),
    	section varchar(2),
    	branch varchar(5),
    	english number(3),
    	maths number(3),
    	CP number(3),
    	BCME number(3)
    );

ALTER TABLE PROGRESS ADD CGPA float;
INSERT INTO PROGRESS VALUES('23PA1A05D7','KOWTHAM','C','CSE',98,99,97,96,9.36);
INSERT INTO PROGRESS VALUES('23PA1A05E0','BHARTH','C','CSE',98,100,99,95,NULL);
INSERT INTO PROGRESS VALUES('23PA1A05E2','DEEPAK','C','CSE',95,90,96,90,NULL);
INSERT INTO PROGRESS VALUES('23PA1A05E5','VENKAT DEEPAK','C','CSE',95,96,98,91,8.96);
INSERT INTO PROGRESS VALUES('23PA1A05F7','ANURAM','C','CSE',89,90,91,92,NULL);
SELECT COUNT(ROLL_NO) FROM PROGRESS;
SELECT ROLL_NO,NAME,SECTION,BRANCH,ENGLISH,MATHS,CP,BCME,(ENGLISH+MATHS+CP+BCME) as totalmarks,((ENGLISH+MATHS+CP+BCME)),AS TOTAL_MARKS FROM PROGRESS ORDER BY TOTAL_MARKS desc;
SELECT ROLL_NO,NAME,SECTION,BRANCH,ENGLISH,MATHS,CP,BCME,(ENGLISH+MATHS+CP+BCME) as totalmarks,((ENGLISH+MATHS+CP+BCME)/400*100) AS PERCENTAGE FROM PROGRESS ORDER BY PERCENTAGE desc;
UPDATE PROGRESS SET CGPA=9.81 WHERE ROLL_NO='23PA1A05E0';

SELECT *FROM PROGRESS;
WHERE NAME LIKE A% OR a%;

SELECT *FROM PROGRESS;


